- _team/dwhswenson.md
- _team/ialibay.md
- _team/mikemhenry.md
- _team/rgowers.md
I'd like to figure out a way to get Richard to be first one the team page, I think I can do that by adding a number prefix to our markdown file.
Also I put everything on the about page, but we should move some content to our landing page, I'm not sure yet what belongs on about and what belongs on the landing page. 
Still need to fix the link color,  add the logo, and add the github social icon.
> More content 

- _team/diegoonolasco.md
Committer: Diego Nolasco <diegonolasco@yahoo.com.br>
On branch diego-update
Changes to be committed:
modified:   _team/diegoonolasco.md
> Diego's blurb update

- assets/images/Squaredcircle_white_text.svg
- index.md
Just handling some spacing issues. I'll merge this immediately; only making a PR of it so there's a clearer record.
> Minor website cleanup

- _posts/2022-03-01-initial-release.md
- _posts/2022-03-15-lomap-conda-forge.md
Made some improvements to the post on the OpenFE 0.1 release. Added a post about the lomap 2.0 release.
This is actual content, so it should be reviewed before going live.
> Improved initial release post; added lomap post

- about.md
This is a start to a new "About" page. I think this hits more of the tone we're looking for (it is a sales pitch) but I'm not sure about some of the information (in particular distinction of how "Fund" works) -- however, I think some information like that is important here, since that's something the audience needs to know.
I'm hoping for significant edits here -- this is just my quick early contribution.
> New "About"

- _sass/customizations.scss
A few more small changes in style. Most notably, we're using `other-blue` for links, which fits better with the color scheme, but doesn't stand out as well as I'd like. We can figure that out later.
I'll make an issue with CSS problems that I find after this is merged in.
> More style

- _sass/customizations.scss
Of the issues in #23, this is the one that bothered me the most. Not sure if this style is what we want, but at least it stays within our branding.
> Fix CSS hover on blog "Read More" buttons to use our color scheme

- README.md
- _config.yml
- _data/navigation.yml
- _projects/_defaults.md
- _projects/gufe.md
- _projects/lomap.md
- _projects/openfe.md
- _sass/customizations.scss
- projects.html
For your consideration. Not that we have to do it -- just something I thought might help us make our pitch:
> Projects page

- about.md
I received positive responses from these companies. It's okay to have them listed on our website, but we should never use their logos.
> partners-2022-10-17

- about.md
AbbVie said yes, and Really said no.
> partners-2022-10-18

- about.md
Kaushik asked me to fix a typo. From Meyers to Myers.
> partners-2022-11-9

- _projects/kartograf.md
> Adding kartograf

- _sass/customizations.scss
I generated some new accent colours with https://coolors.co for the Sphinx theme, here they are so we have a consistent palette!
> Add new colours from sphinx theme

- _team/alyssatravitz.md
- _team/davidmobley.md
- _team/dwhswenson.md
- _team/ialibay.md
- _team/joshhorton.md
- _team/riesben.md
@jthorton @atravitz I've added some placeholder profiles, please do update them as necessary!
> Update team profiles

- _team/alyssatravitz.md
- _team/davidmobley.md
- _team/dwhswenson.md
- _team/joshhorton.md
- _team/riesben.md
adding my bio. Also added "order" values for those of us recently added.
> Updating atravitz profile

- _team/ddotson.md
- _team/dwhswenson.md
- _team/ialibay.md
- _team/ianmkenney.md
- _team/ipulido.md
- _team/jeastwood.md
- _team/riesben.md
> updating ordering

- _projects/cinnabar.md
- _projects/gufe.md
- _projects/kartograf.md
- _projects/konnektor.md
everybody lives in openfree.energy now 😃
> updating project docs urls

- _projects/gufe.md
removing acronym as requested here: https://github.com/OpenFreeEnergy/gufe/issues/508#issuecomment-2803828219
> update gufe description

- _posts/2025-05-06-benchmarking.md
> Add josh's blog post

- _posts/2025-02-04-bespokefit.md
> add news item for bespokefit support

- index.html
> fix buttons on mobile
